### ISSUE TITLE
Unable to find h5diff in your PATH

### ISSUE THREAD

**Issue by gui11aume** [paulsengroup/modle#36]
Hi,

When running the command for the integration test `../test/scripts/modle_integration_test_simple.sh src/modle/modle` I get the error
```
Unable to find h5diff in your PATH
/home/gfilion/miniconda3/envs/tmp/bin/xz
```
There does not seem to be a reference to `h5diff` in the installation notes.
Running `apt install hdf5-tools` on Ubuntu works.
```
$ h5diff --version
h5diff: Version 1.10.4
```
Running command again fails with error
```
h5diff: unknown option "exclude-attribute"
```

**Comment by robomics** [comment]
Hi, thanks for pointing out the issues with `h5diff` and the docs.

I have updated the README with instructions on how to install the deps of the integration test.

Regarding the "unknown option" error: the error occurs because the test script assumes a recent version of `h5diff` (with support for `--exclude-attribute`) is installed.

I have updated the test script so that `--exclude-attribute` is no longer needed.

Both changes are implemented by PR https://github.com/paulsengroup/modle/pull/38.

Feel free to re-open this issue if you are still having issues with the test suite or `h5diff`.
