### ISSUE TITLE
Conan troubleshooting info

### ISSUE THREAD

**Issue by gui11aume** [paulsengroup/modle#37]
The troubleshooting information for the Incorrect or incomplete Conan profile is buried in a hidden paragraph in a different subsection from that where the error occurs. I discovered the troubleshooting information by Googling the error message... which brought me back to the page I started from.

It would make sense to either
1. Instruct the user to update the Conan profile on fresh install, or
1. Put the troubleshooting information front and center next to the command that can fail, or
1. Make a visible note next to the command to check the troubleshooting section.

**Comment by robomics** [comment]
Thanks for the suggestion!

Could you please share the OS and version of Conan on the system where the error occurred?

I am asking because we had similar issues on macOS, but from issue https://github.com/paulsengroup/modle/issues/36 it looks like you are building MoDLE on Ubuntu.

I have moved the troubleshooting section right after the [Compiling MoDLE](https://github.com/paulsengroup/modle#compiling-modle) section.

The troubleshooting section is still minimized to avoid cluttering the README with potentially superfluous information.

Feel free to re-open the issue if you have other suggestions on how to improve the documentation.

**Comment by gui11aume** [comment]
I used Ubuntu 20.04.4 with Linux 5.13.0-27-generic. I installed Conan with the provided command `pip3 install "conan>=1.45"` but I already destroyed the virtual environment I used for the test and I do not remember which version was installed.
